version: 0.2

phases:
  install:
    commands:
      - echo Installing kubectl
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/kubectl

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY

      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

      - echo Updating kubeconfig
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_DEFAULT_REGION
      - kubectl version --client

      - IMAGE_URI=$REPOSITORY_URI:$IMAGE_TAG
      - echo Using image $IMAGE_URI

      - sed -i "s|IMAGE_URI_PLACEHOLDER|$IMAGE_URI|g" ${MANIFEST_PATH}/deployment.yml

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $SERVICE_NAME:$IMAGE_TAG .
      - docker tag $SERVICE_NAME:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG
      - echo Pushing Docker image...
      - docker push $REPOSITORY_URI:$IMAGE_TAG

      - echo Applying Kubernetes manifests
      - kubectl apply -f ${MANIFEST_PATH}/namespace.yml
      - kubectl apply -f ${MANIFEST_PATH}/deployment.yml
      - kubectl apply -f ${MANIFEST_PATH}/service.yml
      # - kubectl apply -f ${MANIFEST_PATH}/ingress.yml

  post_build:
    commands:
      - echo Deployment completed
      - kubectl get pods -A